tau2_bench_resources_server:
  resources_servers:
    tau2_bench:
      entrypoint: app.py
      domain: agent
tau2_agent:
  responses_api_agents:
    tau2_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: tau2_bench_resources_server
      model_server:
        type: responses_api_models
        name: policy_model
      # user_model_server:
      #   type: responses_api_models
      #   name: policy_model
      concurrency: 16
      tau2_domain: airline